### PR TITLE
Update npm dependencies + update rollup js bundling to support bundle.generate returning promise

### PR DESCRIPTION
**Pull request by amrmorsy**
npm dependencies updated
fixed rollup bundling issue after updating dependencies to support bundle.generate now returning a promise
gulp js task now uses Async/Await functions

### CODE REVIEW

**Comment by callmecavs** [comment]
@amrmorsy would you mind taking a shot at updating the `babel` deps to use the new namespaced (`@babel`) packages and `preset-env`? I have them working with `rollup` [here](https://github.com/callmecavs/outset-lib/blob/master/template/rollup.config.js) in a different repo.

No pressure, and I really appreciate what you've already done. In the event that you don't have the time, I'll probably merge this, then update that stuff when I find the time before cutting a new release.

Thank you, this is one of the better pull requests I've received. 😄

**Comment by amrmorsy** [comment]
@callmecavs thank you :) 
I have updated dependencies and gulp file to support @babel and preset-env. I also removed the .babelrc as babel can be configured from gulp file instead as you have in your outset-lib repo

**Comment by amrmorsy** [comment]
another quick note, I changed the gulp-file-include from before only pointing at images folder to point at the entire src folder to give ability to include any html/svg/etc file

**Comment by amrmorsy** [comment]
+ added file sizing report for #16 enhancement

**Comment by amrmorsy** [comment]
Hello, I was wondering if you are planning on merging these updates, when you have time ofcourse :D

thank you !

**Comment by callmecavs** [comment]
@amrmorsy working on it right now. thank you adding the file size stuff to!

**Comment by callmecavs** [comment]
@amrmorsy merged and published a new release. mentioned you in the [release notes](https://github.com/callmecavs/outset/releases/tag/v4.2.0). thank you again! 😃

**Pull request merged**
